<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Google" duration-ms="13186" started-at="2021-11-12T06:06:03Z" finished-at="2021-11-12T06:06:16Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="13186" started-at="2021-11-12T06:06:03Z" finished-at="2021-11-12T06:06:16Z">
      <class name="test.LoginTest">
        <test-method status="PASS" signature="ReportSetup()[pri:0, instance:test.LoginTest@12c8a2c0]" name="ReportSetup" is-config="true" duration-ms="595" started-at="2021-11-12T06:06:03Z" finished-at="2021-11-12T06:06:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReportSetup -->
        <test-method status="PASS" signature="setup()[pri:0, instance:test.LoginTest@12c8a2c0]" name="setup" is-config="true" duration-ms="1600" started-at="2021-11-12T06:06:04Z" finished-at="2021-11-12T06:06:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="ExcelTest()[pri:0, instance:test.LoginTest@12c8a2c0]" name="ExcelTest" duration-ms="2638" started-at="2021-11-12T06:06:05Z" finished-at="2021-11-12T06:06:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ExcelTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:test.LoginTest@12c8a2c0]" name="teardown" is-config="true" duration-ms="72" started-at="2021-11-12T06:06:08Z" finished-at="2021-11-12T06:06:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:test.LoginTest@12c8a2c0]" name="setup" is-config="true" duration-ms="1343" started-at="2021-11-12T06:06:08Z" finished-at="2021-11-12T06:06:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="NegativeLogin(java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest@12c8a2c0]" name="NegativeLogin" duration-ms="2124" started-at="2021-11-12T06:06:09Z" finished-at="2021-11-12T06:06:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Abc@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Abcde123@]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [The email or password you have entered is invalid] but found [The email or password you have entered is invalid.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [The email or password you have entered is invalid] but found [The email or password you have entered is invalid.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at pages.LoginPage.ErrorCheck(LoginPage.java:76)
at test.LoginTest.NegativeLogin(LoginTest.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NegativeLogin -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:test.LoginTest@12c8a2c0]" name="teardown" is-config="true" duration-ms="68" started-at="2021-11-12T06:06:12Z" finished-at="2021-11-12T06:06:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:test.LoginTest@12c8a2c0]" name="setup" is-config="true" duration-ms="1371" started-at="2021-11-12T06:06:12Z" finished-at="2021-11-12T06:06:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="PositiveLogin(java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest@12c8a2c0]" name="PositiveLogin" duration-ms="2142" started-at="2021-11-12T06:06:13Z" finished-at="2021-11-12T06:06:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Abc@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Abcde123@]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at test.LoginTest.PositiveLogin(LoginTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PositiveLogin -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:test.LoginTest@12c8a2c0]" name="teardown" is-config="true" duration-ms="71" started-at="2021-11-12T06:06:16Z" finished-at="2021-11-12T06:06:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="ReportTeardown()[pri:0, instance:test.LoginTest@12c8a2c0]" name="ReportTeardown" is-config="true" duration-ms="250" started-at="2021-11-12T06:06:16Z" finished-at="2021-11-12T06:06:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReportTeardown -->
      </class> <!-- test.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Google -->
</testng-results>
